### ISSUE TITLE
decimal breaks string interpretation

### ISSUE THREAD

**Issue by radiovisual** [miguelmota/commafy#1]
I notice that commafy allows the passing of strings, which is useful in cases like these:

``` js
commafy('1234');
//=> '1,234'
```

But then I also notice that there is no attempt to validate the string as a valid number, so this is allowed, and it works:

``` js
commafy('amount: $1234')
//=> 'amount: $1,234'
```

This seemed like a feature, (although it seems like an 'unintentional' or 'hidden' feature because your unit tests don't test for strings and your documentation doesn't cover it), or a bug disguised as a feature, so I then took it further and tested full strings containing numbers, and this works:

``` js
commafy('one: 1234 two: 1234 three: 1234 four: 1234')
//=> "one: 1,234 two: 1,234 three: 1,234 four: 1,234"
```

**However**, if any of the numbers in the string contain a decimal point, then all numbers after that are ignored. Consider this output where the fourth numerical value is ignored:

``` js
commafy('one: 1234 two: 1234 three: 1234.0 four: 1234')
//=> "one: 1,234 two: 1,234 three: 1,234.0 four: 1234"
```

So if this type of string interpretation is an intended feature, then this is a bug. Otherwise, if this type of behavior is not supported, and you only accept valid numbers (or strings that can be evaluated as numbers), then you might want to add some type of validation check. 

Thanks!

**Comment by radiovisual** [comment]
If the string interpretation is an intended feature, then I might consider treating it like a bug, because if you allow strings to be interpreted, then you can end up commafy-ing values that you wouldn't want commafied, for example, maybe you want the dollar amount in this string commafied, but you wouldn't want the year in the date to be commafied:

``` js
commafy('amount: $1234 date: Jan 12 1999')
//=> "amount: $1,234 date: Jan 12 1,999"
```

This is an example of how commafying strings that can't be parsed as numbers can lead to some undesirable behavior.

**Comment by radiovisual** [comment]
I am happy to submit a pull request if you consider this type of string interpretation a bug, and only want to accept numbers (or strings that can be parsed to numbers).

**Comment by miguelmota** [comment]
@radiovisual initially this module was meant for numbers only so what you mentioned is a _bug disguised as a feature_ due to my lack of unit tests.

The module is now updated to only accept numeric (numbers or strings that are numbers) values  otherwise it will return the value back.

The functionality of the module should be kept simple to just numeric values and leave the parsing of complex strings up to the user.

``` javascript
commafy('1234');
// '1,234'
```

``` javascript
commafy('$1234');
// '$1234'
```

``` javascript
commafy('amount: $1234');
// 'amount: $1234'
```

``` javascript
commafy('one: 1234 two: 1234 three: 1234.0 four: 1234')
// 'one: 1234 two: 1234 three: 1234.0 four: 1234'
```

Thank you so much for bringing this up! : )

**Comment by radiovisual** [comment]
no problem! I am happy to help! :smile: :+1:
