### ISSUE TITLE
attempts to commafy non-numeric strings and objects

### ISSUE THREAD

**Issue by radiovisual** [miguelmota/commafy#2]
Only valid numeric strings should be 'commafied', yet commafy will attempt to commafy non-numeric strings:

``` js
commafy('123456789abcdefg123');
//=> "123,456,789abcdefg,123"
```

``` js
commafy('abc123def');
//=> ""abc,123def""
```

You can even take this further: commafy will also attempt to commafy anything you pass it:

``` js
// accepts an object
commafy({one:1234});
//=> "[object Object]"

// accepts an array
commafy([1234,5678]);
//=> "1,234,5,678"

// accepts a boolean
commafy(true);
//=> "true"

// accepts a date
commafy(new Date());
//=> "Sat Feb 06 2,016 10:20:32 GMT+0,000 (GMT)"
```

It would be useful if commafy complained if you passed it something that isn't numeric or commafy-able to help catch bugs in the application that is running commafy.

**Comment by radiovisual** [comment]
I just verified that these issues go away now that you have [written checks to only allow numeric values](https://github.com/miguelmota/commafy/commit/271d0f70ff4ed25fce2f065c7fad7a30fa083ba4) in your latest commit, so I will close this issue, but before I do, I just wanted to say that I think it could strengthen your API if commafy threw an error if it receives something other than a numeric string, this could help developers catch unintentional bugs or "silent fails" by reminding developers how the module is intended to be used.

If commafy threw an error it helps developers find bugs by saying: 

> "hey, I can only commafy numeric strings, but you gave me an object, or a function, so something must be wrong in your application..."

But currently, commafy just keeps going even if it receives something it can't work with, and if you are giving an object or a function or a date to commafy, then clearly something is wrong. So I personally think throwing an error is a better way to go, but in the end, it's up to you!

Thanks again! :+1:

**Comment by miguelmota** [comment]
@radiovisual thank you for all your constructive feedback. Instead of throwing errors I decided to follow the approach of stringifying the input value regardless of the type. This approach is seen in popular libraries such as lodash, where throwing errors is typically avoided. This way the return value is always a string and the behaviour is predictable.

**Comment by radiovisual** [comment]
no problem! happy to help! :+1:
